query homepage_stories_products($pageSize: Int) {
  homepage_stories_products(pageSize: $pageSize) {
    items {
      uid
      id
      url_key
      product_likes
      ins_days
      name
      short_description_alike
      ins_tags
      ins_city
      is_liked
      # ins_custom_attributes {
      #   ins_tags_label
      #   is_liked
      #   ins_city
      # }
      insider_data {
        insider_name
        insider_logo
        insider_id
        profile_url
        is_followed
        username
      }
      ins_traveller_type
      image {
        url
      }
      # itinerary {
      #   icons {
      #     icon_url
      #     label
      #     count
      #   }
      # }
      icons {
        icon_url
        label
        count
      }
      sku
      type_id
      price_range {
        minimum_price {
          regular_price {
            value
            currency
          }
        }
      }
      dynamicAttributes(fields: ["ins_city", "ins_tags"])
    }
  }
}
